import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Layout from '../components/Layout'
import developer from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center justify-center w-full min-h-screen text-light'>
        <Layout className='pt-0' >
          <div className='flex lg:flex-col items-center justify-between w-full bg-light'>
            <div className='w-1/2 md:w-full'>
              <Image src={developer} alt='image' className='w-full h-auto lg:hidden md:inline-block md:w-full' priority 
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"/>
            </div>
            <div className='flex flex-col items-center self-center text-dark w-1/2 lg:text-center lg:w-full'>
              <AnimatedText text="turning vision into reality with code and design." className='!text-5xl !text-start lg:!text-6xl md:!text-4xl lg:!text-center sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link href="/dummy.pdf" target="_blank" className="flex items-center p-2.5 px-6 bg-dark text-light rounded-lg font-semibold text-lg hover:bg-light hover:text-dark border-2 border-dark mr-4">Resume <LinkArrow /></Link>
                <Link href="mailto:musaibx@gmail.com" target="_blank" className="text-dark font-semibold underline text-lg">Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 w-24 inline-block'>
          <Image src={lightBulb} className='w-full h-auto md:hidden'></Image>
        </div>
      </main>
    </>
  )
}