import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Layout from '../components/Layout'
import developer from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <article className='flex items-center justify-center w-full min-h-screen text=dark dark:text-light sm:items-start'>
        <Layout className='!pt-0 md:!pt-16 sm:!pt-16' >
          <div className='flex items-start justify-between w-full md:flex-col'>
            <div className='w-1/2 md:inline-block md:w-full lg:hidden'>
              <Image src={developer} alt='image' className='w-full h-auto' priority 
              sizes="100vw"/>
            </div>
            <div className='flex flex-col items-center self-center text-dark w-1/2 lg:text-center lg:w-full dark:text-light'>
              <AnimatedText text="turning vision into reality with code and design." className='!text-6xl !text-left xl:!text-5xl lg:!text-6xl md:!text-4xl lg:!text-center sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link href="/dummy.pdf" target="_blank" className="flex items-center rounded-lg border-2 mr-4 border-solid bg-dark p-2.5 px-6 text-lg font-semibold capitalize text-light hover:border-dark hover:bg-transparent hover:text-dark  dark:bg-light dark:text-dark dark:hover:border-light dark:hover:bg-dark dark:hover:text-light md:p-2 md:px-4 md:text-base">Resume <LinkArrow className="ml-1 !w-6 md:!w-4" /></Link>
                <Link href="mailto:musaibx@gmail.com" target="_blank" className="text-dark font-semibold underline text-lg dark:text-light">Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 w-24 inline-block md:hidden'>
          <Image src={lightBulb} className='relative w-full h-auto'></Image>
        </div>
      </article>
    </>
  )
}